scrapers:
    - name: file://testdata/https-realpython-github-io-fake-jobs.html
      url: file://testdata/https-realpython-github-io-fake-jobs.html
      item: div.column.is-half > div.card > div.card-content
      fields:
        - name: field-0
          type: url
          location:
            - selector: footer.card-footer > a.card-footer-item:nth-child(2)
              attr: href
          can_be_empty: true
        - name: field-1
          type: text
          location:
            - selector: div.content > p.location
          can_be_empty: true
        - name: field-2
          type: text
          location:
            - selector: div.media > div.media-content > h3.company.is-6.subtitle
          can_be_empty: true
        - name: field-3
          type: text
          location:
            - selector: div.media > div.media-content > h2.is-5.title
          can_be_empty: true
