package generate

import (
	"context"
	"slices"
	"testing"

	"github.com/findyourpaths/goskyr/observability"
)

// TestCheckAndUpdateLocPropsVaryingPostClasses verifies that checkAndUpdateLocProps
// merges nodes that differ only in CMS-generated per-page classes like WordPress
// post-9762 vs post-8954. These classes are stripped before comparison.
func TestCheckAndUpdateLocPropsVaryingPostClasses(t *testing.T) {
	// Page 1: div.content-area.post-1001.product.type-product.status-publish > h1.product-title
	// Page 2: div.content-area.post-2002.product.type-product.status-publish > h1.product-title
	old := &locationProps{
		textIndex: 0,
		attr:      "",
		path: path{
			{tagName: "div", classes: []string{"content-area", "post-1001", "product", "type-product", "status-publish"}},
			{tagName: "h1", classes: []string{"product-title", "entry-title"}},
		},
		count:    1,
		examples: []string{"Workshop A"},
	}

	new := &locationProps{
		textIndex: 0,
		attr:      "",
		path: path{
			{tagName: "div", classes: []string{"content-area", "post-2002", "product", "type-product", "status-publish"}},
			{tagName: "h1", classes: []string{"product-title", "entry-title"}},
		},
		count:    1,
		examples: []string{"Workshop B"},
	}

	merged := checkAndUpdateLocProps(old, new)
	if !merged {
		t.Fatal("expected paths to merge (differ only in post-NNNNN) but they did not")
	}

	if old.count != 2 {
		t.Errorf("expected count 2, got %d", old.count)
	}

	// The merged path should have post-NNNNN stripped
	wrapperClasses := old.path[0].classes
	if !slices.Contains(wrapperClasses, "content-area") {
		t.Error("expected 'content-area' in merged classes")
	}
	if !slices.Contains(wrapperClasses, "product") {
		t.Error("expected 'product' in merged classes")
	}
	if slices.Contains(wrapperClasses, "post-1001") {
		t.Error("'post-1001' should be stripped from merged classes")
	}
	if slices.Contains(wrapperClasses, "post-2002") {
		t.Error("'post-2002' should be stripped from merged classes")
	}

	// h1 classes should be fully preserved (no auto-generated classes)
	h1Classes := old.path[1].classes
	if len(h1Classes) != 2 || !slices.Contains(h1Classes, "product-title") || !slices.Contains(h1Classes, "entry-title") {
		t.Errorf("expected h1 classes [product-title, entry-title], got %v", h1Classes)
	}
}

// TestCheckAndUpdateLocPropsBeaverBuilderContentIDs verifies that fl-builder-content-NNNN
// classes are stripped, allowing pages with different Beaver Builder content IDs to merge.
func TestCheckAndUpdateLocPropsBeaverBuilderContentIDs(t *testing.T) {
	old := &locationProps{
		textIndex: 0,
		attr:      "",
		path: path{
			{tagName: "div", classes: []string{"fl-builder-content", "fl-builder-content-6725", "fl-builder-global-templates-locked", "product"}},
		},
		count:    1,
		examples: []string{"val1"},
	}

	new := &locationProps{
		textIndex: 0,
		attr:      "",
		path: path{
			{tagName: "div", classes: []string{"fl-builder-content", "fl-builder-content-8090", "fl-builder-global-templates-locked", "product"}},
		},
		count:    1,
		examples: []string{"val2"},
	}

	merged := checkAndUpdateLocProps(old, new)
	if !merged {
		t.Fatal("expected paths to merge (differ only in fl-builder-content-NNNN) but they did not")
	}

	classes := old.path[0].classes
	if slices.Contains(classes, "fl-builder-content-6725") {
		t.Error("fl-builder-content-6725 should be stripped")
	}
	if slices.Contains(classes, "fl-builder-content-8090") {
		t.Error("fl-builder-content-8090 should be stripped")
	}
	if !slices.Contains(classes, "fl-builder-content") {
		t.Error("fl-builder-content (no number) should be preserved")
	}
	if !slices.Contains(classes, "product") {
		t.Error("product should be preserved")
	}
}

// TestCheckAndUpdateLocPropsStructurallyDifferent verifies that nodes with different
// structural classes (not just auto-generated) are NOT merged.
func TestCheckAndUpdateLocPropsStructurallyDifferent(t *testing.T) {
	old := &locationProps{
		textIndex: 0,
		attr:      "",
		path: path{
			{tagName: "div", classes: []string{"header", "nav-bar", "main-menu"}},
		},
		count:    1,
		examples: []string{"Home"},
	}

	new := &locationProps{
		textIndex: 0,
		attr:      "",
		path: path{
			{tagName: "div", classes: []string{"footer", "nav-bar", "copyright"}},
		},
		count:    1,
		examples: []string{"(c) 2026"},
	}

	merged := checkAndUpdateLocProps(old, new)
	if merged {
		t.Fatal("expected paths NOT to merge (structurally different) but they did")
	}
}

// TestFilterAutoGeneratedClasses verifies the regex patterns.
func TestFilterAutoGeneratedClasses(t *testing.T) {
	tests := []struct {
		input    []string
		expected []string
	}{
		{
			input:    []string{"content-area", "post-1001", "product", "type-product"},
			expected: []string{"content-area", "product", "type-product"},
		},
		{
			input:    []string{"fl-builder-content", "fl-builder-content-6725", "fl-builder-global-templates-locked"},
			expected: []string{"fl-builder-content", "fl-builder-global-templates-locked"},
		},
		{
			input:    []string{"postid-456", "page-id-789", "wp-theme-bb"},
			expected: []string{"wp-theme-bb"},
		},
		{
			input:    []string{"product-title", "entry-title"},
			expected: []string{"product-title", "entry-title"},
		},
	}

	for _, tt := range tests {
		result := filterAutoGeneratedClasses(tt.input)
		if len(result) != len(tt.expected) {
			t.Errorf("filterAutoGeneratedClasses(%v) = %v, want %v", tt.input, result, tt.expected)
			continue
		}
		for i, r := range result {
			if r != tt.expected[i] {
				t.Errorf("filterAutoGeneratedClasses(%v)[%d] = %q, want %q", tt.input, i, r, tt.expected[i])
			}
		}
	}
}

func TestFindClustersDoesNotMutateRootBackedFieldPaths(t *testing.T) {
	cardPath := path{
		{tagName: "body"},
		{tagName: "div", classes: []string{"container"}},
		{tagName: "div", classes: []string{"main", "current"}},
		{tagName: "article", classes: []string{"card", "article"}},
		{tagName: "div", classes: []string{"card-body"}},
		{tagName: "div", classes: []string{"name"}},
	}
	rootSelector := cardPath[:2]
	cardLP := &locationProps{path: cardPath, count: 10, examples: []string{"Abby"}}
	formLP := &locationProps{
		path: path{
			{tagName: "body"},
			{tagName: "div", classes: []string{"container"}},
			{tagName: "form"},
			{tagName: "select"},
		},
		count:    10,
		examples: []string{"filter"},
	}

	ctx := context.Background()
	endFn, err := observability.InitAll(ctx, t.TempDir(), true)
	if err != nil {
		t.Fatalf("%v", err)
	}
	defer func() {
		if err := endFn(); err != nil {
			t.Fatalf("%v", err)
		}
	}()

	clusters := findClusters(ctx, []*locationProps{cardLP, formLP}, rootSelector)
	cardKey := "body > div.container > div.main.current"
	if _, ok := clusters[cardKey]; !ok {
		t.Fatalf("missing card cluster %q; got keys %v", cardKey, clusters)
	}
	if got := cardLP.path[2].string(); got != "div.main.current" {
		t.Fatalf("card path mutated at cluster node: got %q", got)
	}
	if got := clonePath(clusters[cardKey][0].path[:len(rootSelector)+1]).string(); got != cardKey {
		t.Fatalf("recursive root = %q, want %q", got, cardKey)
	}
}

func TestDateDominatedText(t *testing.T) {
	cases := []struct {
		text string
		want bool
	}{
		// Schedule rows: mostly date text.
		{text: "Saturday, June 27, 2026 | 6 pm - 9 pm", want: true},
		{text: "17:00 PM – 21:00 PM (SAST)", want: true},
		{text: "Begins: Friday, 03-Jul-2026", want: true},
		{text: "2026-08-29 @10:00 AM - 2026-08-30@05:00 PM", want: true},
		{text: "Monday, June 15, 2026 6:00 - 7:30 pm CST", want: true},
		// Titles and prose that merely embed a date: mostly words.
		{text: "Development by Design | Singapore | July 7 - 10, 2026", want: false},
		{text: "Type, Teach, Transform through the 27 Enneagram Subtypes | Virtual | July 17-24, 2026", want: false},
		{text: "The Art of Enneagram Typing and Training | VIRTUAL | August 17 - 28, 2026", want: false},
		{text: "Join us on Saturday, June 27 for a wonderful workshop about the nine personality types and their wings", want: false},
		{text: "", want: false},
	}
	for _, tc := range cases {
		if got := dateDominatedText(tc.text); got != tc.want {
			t.Errorf("dateDominatedText(%q) = %v, want %v", tc.text, got, tc.want)
		}
	}
}
